version: '3.7'
services:
    web:
        image: nginx:latest
        environment:
            TZ: ${TZ}
        container_name: nginx-pdf
        ports:
            - "80:80"
        volumes:
            - "./nginx.conf:/etc/nginx/conf.d/nginx.conf"
            - "./app:/app"
        links:
            - php
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        container_name: php-pdf
        environment:
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        volumes:
            - "./app:/app"
        links:
            - mysql
    mysql:
        image: mariadb:latest
        container_name: mysql-pdf
        ports:
            - "3306:3306"
        environment:
            TZ: ${TZ}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - "./mysql/data:/var/lib/mysql"
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
            - "./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: unless-stopped
volumes:
    mysqldata: {}
